# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare_env:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -U pytest-github-actions-annotate-failures
        pip install -U pytest-html
  
  pytest:
    runs-on: ubuntu-latest
    
    - name: Test with pytest
      run: |
        pytest --html=report.html --self-contained-html

  report:
    runs-on: ubuntu-latest

    - name: Archive pytest HTML report
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          report.html

    - name: codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
