# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U pytest-github-actions-annotate-failures
          pip install -U pytest-html
          pip install -U pytest-cov
    
      - name: Test with pytest
        run: |
          pytest --html=${{ matrix.os }}.html --self-contained-html --cov=dlpt --cov-report=xml --cov-report term-missing

      - name: Archive pytest HTML report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Pytest HTML report
          path: |
            ${{ matrix.os }}.html

      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
